# Generated by Django 5.1 on 2026-06-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moods', '0001_initial'),
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionscore',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_scores', to='relationships.relationship'),
        ),
    ]
