# Generated by Django 5.1 on 2026-06-05 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moods', '0002_initial'),
        ('relationships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to='relationships.relationship'),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='connectionscore',
            unique_together={('user', 'relationship', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together={('user', 'relationship', 'date')},
        ),
    ]
